variable "environment" {
  description = "Environment name (dev/staging/prod)"
  type        = string
}

variable "db_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage" {
  description = "Initial RDS storage, in GB (20 is the AWS-enforced minimum for gp3 PostgreSQL)"
  type        = number
  default     = 20
}

variable "db_max_allocated_storage_percent" {
  description = "Storage autoscaling ceiling, as a percentage of db_allocated_storage (250 = grows up to 2.5x the initial size before you'd need to intervene manually)"
  type        = number
  default     = 250
}

variable "db_name" {
  description = "Initial database name created inside the RDS instance"
  type        = string
  default     = "paymentorders"
}

variable "db_username" {
  description = "Master username — the password itself is auto-generated by RDS into Secrets Manager, never set here"
  type        = string
  default     = "postgres"
}
